config/routes.rb
Rails.application.routes.draw do
  root to: 'urls#index'

  post '/urls' => 'urls#create'
  get '/urls/:id' => 'urls#show',  :as => 'show_routes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  before_validation :set_short_url
  validates :long_url, :short_url, presence: true
  validates :short_url, uniqueness: true
  validates_format_of :long_url, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i

  private

  def set_short_url
    self.short_url = "http://localhost:3000/" + generate_short_url
  end

  def generate_short_url
    loop do
      short_url = SecureRandom.uuid[0..6]
      break short_url unless Url.exists?(short_url: short_url)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @url = Url.new
  end

  def show
    @url = Url.find(params[:id])
  end

  def create
    @url = Url.new(url_params)
    if @url.save
      redirect_to show_routes_path(@url.id)
    else
      render action: :index
    end
  end

  private

  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>Short Me</h1>

<%= form_for @url, url: urls_path do |f| %>
  <%= f.text_field :long_url %>
  <%= f.submit %>
<% end %>

app/views/urls/show.html.erb
<h1>Go from here</h1>

<%= link_to @url.short_url, @url.long_url %>